# Generated by Django 2.0.3 on 2018-07-22 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.CharField(max_length=250)),
                ('drop', models.CharField(max_length=250)),
                ('picklat', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=10)),
                ('picklong', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=10)),
                ('droplat', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=10)),
                ('droplong', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=10)),
                ('instructions', models.TextField(max_length=2500)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('order_time', models.TimeField(auto_now_add=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_canceled', models.BooleanField(default=False)),
                ('is_seen', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('user_read', models.BooleanField(default=False)),
                ('exec_read', models.BooleanField(default=False)),
                ('amount', models.IntegerField(default=None, null=True)),
                ('duration_exec_pick', models.IntegerField(default=None, null=True)),
                ('duration_pick_drop', models.IntegerField(default=None, null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
