# Generated by Django 2.0.3 on 2018-07-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinfo',
            name='contact_drop',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='contact_pick',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
