# Generated by Django 2.0.3 on 2018-10-31 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181101_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinfo',
            name='droplat',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='droplong',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='picklat',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='picklong',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=10, null=True),
        ),
    ]
