# Generated by Django 2.0.3 on 2019-03-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181101_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinfo',
            name='drop_home_number',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='drop_landmark',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='pickup_home_number',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='pickup_landmark',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
