# Generated by Django 2.0.3 on 2019-04-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190321_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinfo',
            name='other_package_content',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='package_content',
            field=models.CharField(choices=[('Documents Or Books', 'Documents Or Books'), ('Gadgets Or Accesories', 'Gadgets Or Accesories'), ('Clothes Or Outfits', 'Clothes Or Outfits'), ('Household Items', 'Household Items'), ('Food Or Bevarages', 'Food Or Bevareges'), ('Other', 'Other')], default='Documents Or Books', max_length=100),
        ),
    ]
