# Generated by Django 2.0.3 on 2019-04-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190402_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinfo',
            name='instructions',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='package_content',
            field=models.CharField(choices=[('Documents Or Books', 'Documents Or Books'), ('Gadgets Or Accesories', 'Gadgets Or Accesories'), ('Clothes Or Outfits', 'Clothes Or Outfits'), ('Food Or Beverages', 'Food Or Beverages'), ('Household Items', 'Household Items'), ('Other', 'Other')], default='Documents Or Books', max_length=100),
        ),
    ]
