# Generated by Django 2.0.3 on 2018-07-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180722_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='recent_order_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
