# Generated by Django 2.0.3 on 2019-01-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180722_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_user_verified',
            field=models.BooleanField(default=False),
        ),
    ]
