# Generated by Django 2.0.3 on 2019-01-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190125_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='offer_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
